CPPFILE = MessageDistributionSystemTest.cpp MessageDistributionSystem.cpp

all:
	g++ -g $(CPPFILE) -o msgdistsys /home/bjarke/skole/ISU/Exercises/9/osapi-src/lib/host/debug/libOSApi.a -I/home/bjarke/skole/ISU/Exercises/9/osapi-src/inc -DOS_LINUX -lpthread -lrt
